import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
  <nav className="bg-blue-600 text-white p-4 flex gap-6">
  <Link href="/">Home</Link>
  <Link href="/about">about</Link>
  <Link href="/services">Services</Link>
  <Link href="/informations">Informations</Link>
  <Link href="/contact">Contact</Link>
</nav>

  {children}
</body>
    </html>
  );
}
